export const categories = [
    {category: "Medical"},
    {category: "Memorial"},
    {category: "Emergency"},
    {category: "Nonprofit"},
    {category: "Education"},
    {category: "Animals"},
    {category: "Community"},
    {category: "Competition"},
    {category: "Creative"},
    {category: "Event"},
    {category: "Faith"},
    {category: "Family"},
    {category: "Sports"},
    {category: "Travel"},
    {category: "Volunteer"},
    {category: "Wishes"},
    {category: "Others"},
  ];
  