export const states = [
    {state: "Uttar Pradesh"},
    {state: "Delhi"},
    {state: "Haryana"},
    {state: "Rajasthan"}
]

export const cities = {
  andaman_and_nicobar_islands: ["Port Blair"],
  andhra_pradesh: [
    "Adoni",
    "Amalapuram",
    "Anakapalle",
    "Anantapur",
    "Bapatla",
    "Bheemunipatnam",
    "Bhimavaram",
    "Bobbili",
    "Chilakaluripet",
    "Chirala",
    "Chittoor",
    "Dharmavaram",
    "Eluru",
    "Gooty",
    "Gudivada",
    "Gudur",
    "Guntakal",
    "Guntur",
    "Hindupur",
    "Jaggaiahpet",
    "Jammalamadugu",
    "Kadapa",
    "Kadiri",
    "Kakinada",
    "Kandukur",
    "Kavali",
    "Kovvur",
    "Kurnool",
    "Macherla",
    "Machilipatnam",
    "Madanapalle",
    "Mandapeta",
    "Markapur",
    "Nagari",
    "Naidupet",
    "Nandyal",
    "Narasapuram",
    "Narasaraopet",
    "Narsipatnam",
    "Nellore",
    "Nidadavole",
    "Nuzvid",
    "Ongole",
    "Palacole",
    "Palasa Kasibugga",
    "Parvathipuram",
    "Pedana",
    "Peddapuram",
    "Pithapuram",
    "Ponnur",
    "Proddatur",
    "Punganur",
    "Puttur",
    "Rajahmundry",
    "Rajam",
    "Rajampet",
    "Ramachandrapuram",
    "Rayachoti",
    "Rayadurg",
    "Renigunta",
    "Repalle",
    "Salur",
    "Samalkot",
    "Sattenapalle",
    "Srikakulam",
    "Srikalahasti",
    "Srisailam Project (Right Flank Colony) Township",
    "Sullurpeta",
    "Tadepalligudem",
    "Tadpatri",
    "Tanuku",
    "Tenali",
    "Tirupati",
    "Tiruvuru",
    "Tuni",
    "Uravakonda",
    "Venkatagiri",
    "Vijayawada",
    "Vinukonda",
    "Visakhapatnam",
    "Vizianagaram",
    "Yemmiganur",
    "Yerraguntla",
  ],
  arunachal_pradesh: ["Naharlagun", "Pasighat"],
  assam: [
    "Barpeta",
    "Bongaigaon City",
    "Dhubri",
    "Dibrugarh",
    "Diphu",
    "Goalpara",
    "Guwahati",
    "Jorhat",
    "Karimganj",
    "Lanka",
    "Lumding",
    "Mangaldoi",
    "Mankachar",
    "Margherita",
    "Mariani",
    "Marigaon",
    "Nagaon",
    "Nalbari",
    "North Lakhimpur",
    "Rangia",
    "Sibsagar",
    "Silapathar",
    "Silchar",
    "Tezpur",
    "Tinsukia",
  ],
  bihar: [
    "Araria",
    "Arrah",
    "Arwal",
    "Asarganj",
    "Aurangabad",
    "Bagaha",
    "Barh",
    "Begusarai",
    "Bettiah",
    "Bhabua",
    "Bhagalpur",
    "Buxar",
    "Chhapra",
    "Darbhanga",
    "Dehri-on-Sone",
    "Dumraon",
    "Forbesganj",
    "Gaya",
    "Gopalganj",
    "Hajipur",
    "Jamalpur",
    "Jamui",
    "Jehanabad",
    "Katihar",
    "Kishanganj",
    "Lakhisarai",
    "Lalganj",
    "Madhepura",
    "Madhubani",
    "Maharajganj",
    "Mahnar Bazar",
    "Makhdumpur",
    "Maner",
    "Manihari",
    "Marhaura",
    "Masaurhi",
    "Mirganj",
    "Mokameh",
    "Motihari",
    "Motipur",
    "Munger",
    "Murliganj",
    "Muzaffarpur",
    "Narkatiaganj",
    "Naugachhia",
    "Nawada",
    "Nokha",
    "Patna",
    "Piro",
    "Purnia",
    "Rafiganj",
    "Rajgir",
    "Ramnagar",
    "Raxaul Bazar",
    "Revelganj",
    "Rosera",
    "Saharsa",
    "Samastipur",
    "Sasaram",
    "Sheikhpura",
    "Sheohar",
    "Sherghati",
    "Silao",
    "Sitamarhi",
    "Siwan",
    "Sonepur",
    "Sugauli",
    "Sultanganj",
    "Supaul",
    "Warisaliganj",
  ],
  chandigarh: ["Chandigarh"],
  chhattisgarh: [
    "Ambikapur",
    "Bhatapara",
    "Bhilai Nagar",
    "Bilaspur",
    "Chirmiri",
    "Dalli-Rajhara",
    "Dhamtari",
    "Durg",
    "Jagdalpur",
    "Korba",
    "Mahasamund",
    "Manendragarh",
    "Mungeli",
    "Naila Janjgir",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sakti",
    "Tilda Newra",
  ],
  dadra_and_nagar_haveli: ["Silvassa"],
  delhi: [{city: "Delhi"}, {city: "New Delhi"}],
  goa: ["Mapusa", "Margao", "Marmagao", "Panaji"],
  gujarat: [
    "Adalaj",
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Anjar",
    "Ankleshwar",
    "Bharuch",
    "Bhavnagar",
    "Bhuj",
    "Chhapra",
    "Deesa",
    "Dhoraji",
    "Godhra",
    "Jamnagar",
    "Kadi",
    "Kapadvanj",
    "Keshod",
    "Khambhat",
    "Lathi",
    "Limbdi",
    "Lunawada",
    "Mahesana",
    "Mahuva",
    "Manavadar",
    "Mandvi",
    "Mangrol",
    "Mansa",
    "Mahemdabad",
    "Modasa",
    "Morvi",
    "Nadiad",
    "Navsari",
    "Padra",
    "Palanpur",
    "Palitana",
    "Pardi",
    "Patan",
    "Petlad",
    "Porbandar",
    "Radhanpur",
    "Rajkot",
    "Rajpipla",
    "Rajula",
    "Ranavav",
    "Rapar",
    "Salaya",
    "Sanand",
    "Savarkundla",
    "Sidhpur",
    "Sihor",
    "Songadh",
    "Surat",
    "Talaja",
    "Thangadh",
    "Tharad",
    "Umbergaon",
    "Umreth",
    "Una",
    "Unjha",
    "Upleta",
    "Vadnagar",
    "Vadodara",
    "Valsad",
    "Vapi",
    "Vapi",
    "Veraval",
    "Vijapur",
    "Viramgam",
    "Visnagar",
    "Vyara",
    "Wadhwan",
    "Wankaner",
  ],
  haryana: [
    {city: "Bahadurgarh"},
    {city: "Bhiwani"},
    {city: "Charkhi Dadri"},
    {city: "Faridabad"},
    {city: "Fatehabad"},
    {city: "Gohana"},
    {city: "Gurgaon"},
    {city: "Hansi"},
    {city: "Hisar"},
    {city: "Jind"},
    {city: "Kaithal"},
    {city: "Karnal"},
    {city: "Ladwa"},
    {city: "Mahendragarh"},
    {city: "Mandi Dabwali"},
    {city: "Narnaul"},
    {city: "Narwana"},
    {city: "Palwal"},
    {city: "Panchkula"},
    {city: "Panipat"},
    {city: "Pehowa"},
    {city: "Pinjore"},
    {city: "Rania"},
    {city: "Ratia"},
    {city: "Rewari"},
    {city: "Rohtak"},
    {city: "Safidon"},
    {city: "Samalkha"},
    {city: "Sarsod"},
    {city: "Shahbad"},
    {city: "Sirsa"},
    {city: "Sohna"},
    {city: "Sonipat"},
    {city: "Taraori"},
    {city: "Thanesar"},
    {city: "Tohana"},
    {city: "Yamunanagar"},
  ],
  himachal_pradesh: [
    "Mandi",
    "Nahan",
    "Palampur",
    "Shimla",
    "Solan",
    "Sundarnagar",
  ],
  jammu_and_kashmir: [
    "Anantnag",
    "Baramula",
    "Jammu",
    "Kathua",
    "Punch",
    "Rajauri",
    "Sopore",
    "Srinagar",
    "Udhampur",
  ],
  jharkhand: [
    "Adityapur",
    "Bokaro Steel City",
    "Chaibasa",
    "Chatra",
    "Chirkunda",
    "Medininagar (Daltonganj)",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "Giridih",
    "Gumia",
    "Hazaribag",
    "Jamshedpur",
    "Jhumri Tilaiya",
    "Lohardaga",
    "Madhupur",
    "Mihijam",
    "Musabani",
    "Pakaur",
    "Patratu",
    "Phusro",
    "Ramgarh",
    "Ranchi",
    "Sahibganj",
    "Saunda",
    "Simdega",
    "Tenu dam-cum-Kathhara",
  ],
  karnataka: [
    "Adyar",
    "Afzalpur",
    "Arsikere",
    "Athni",
    "Bengaluru",
    "Belagavi",
    "Ballari",
    "Chikkamagaluru",
    "Davanagere",
    "Gokak",
    "Hubli-Dharwad",
    "Karwar",
    "Kolar",
    "Lakshmeshwar",
    "Lingsugur",
    "Maddur",
    "Madhugiri",
    "Madikeri",
    "Magadi",
    "Mahalingapura",
    "Malavalli",
    "Malur",
    "Mandya",
    "Mangaluru",
    "Manvi",
    "Mudalagi",
    "Mudabidri",
    "Muddebihal",
    "Mudhol",
    "Mulbagal",
    "Mundargi",
    "Nanjangud",
    "Nargund",
    "Navalgund",
    "Nelamangala",
    "Pavagada",
    "Piriyapatna",
    "Puttur",
    "Rabkavi Banhatti",
    "Raayachuru",
    "Ranebennuru",
    "Ramanagaram",
    "Ramdurg",
    "Ranibennur",
    "Robertson Pet",
    "Ron",
    "Sadalagi",
    "Sagara",
    "Sakaleshapura",
    "Sindagi",
    "Sanduru",
    "Sankeshwara",
    "Saundatti-Yellamma",
    "Savanur",
    "Sedam",
    "Shahabad",
    "Shahpur",
    "Shiggaon",
    "Shikaripur",
    "Shivamogga",
    "Surapura",
    "Shrirangapattana",
    "Sidlaghatta",
    "Sindhagi",
    "Sindhnur",
    "Sira",
    "Sirsi",
    "Siruguppa",
    "Srinivaspur",
    "Tarikere",
    "Tekkalakote",
    "Terdal",
    "Talikota",
    "Tiptur",
    "Tumkur",
    "Udupi",
    "Vijayapura",
    "Wadi",
    "Yadgir",
  ],
  karnatka: ["Mysore"],
  kerala: [
    "Adoor",
    "Alappuzha",
    "Attingal",
    "Chalakudy",
    "Changanassery",
    "Cherthala",
    "Chittur-Thathamangalam",
    "Guruvayoor",
    "Kanhangad",
    "Kannur",
    "Kasaragod",
    "Kayamkulam",
    "Kochi",
    "Kodungallur",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Kunnamkulam",
    "Malappuram",
    "Mattannur",
    "Mavelikkara",
    "Mavoor",
    "Muvattupuzha",
    "Nedumangad",
    "Neyyattinkara",
    "Nilambur",
    "Ottappalam",
    "Palai",
    "Palakkad",
    "Panamattom",
    "Panniyannur",
    "Pappinisseri",
    "Paravoor",
    "Pathanamthitta",
    "Peringathur",
    "Perinthalmanna",
    "Perumbavoor",
    "Ponnani",
    "Punalur",
    "Puthuppally",
    "Koyilandy",
    "Shoranur",
    "Taliparamba",
    "Thiruvalla",
    "Thiruvananthapuram",
    "Thodupuzha",
    "Thrissur",
    "Tirur",
    "Vaikom",
    "Varkala",
    "Vatakara",
  ],
  madhya_pradesh: [
    "Alirajpur",
    "Ashok Nagar",
    "Balaghat",
    "Bhopal",
    "Ganjbasoda",
    "Gwalior",
    "Indore",
    "Itarsi",
    "Jabalpur",
    "Lahar",
    "Maharajpur",
    "Mahidpur",
    "Maihar",
    "Malaj Khand",
    "Manasa",
    "Manawar",
    "Mandideep",
    "Mandla",
    "Mandsaur",
    "Mauganj",
    "Mhow Cantonment",
    "Mhowgaon",
    "Morena",
    "Multai",
    "Mundi",
    "Murwara (Katni)",
    "Nagda",
    "Nainpur",
    "Narsinghgarh",
    "Narsinghgarh",
    "Neemuch",
    "Nepanagar",
    "Niwari",
    "Nowgong",
    "Nowrozabad (Khodargama)",
    "Pachore",
    "Pali",
    "Panagar",
    "Pandhurna",
    "Panna",
    "Pasan",
    "Pipariya",
    "Pithampur",
    "Porsa",
    "Prithvipur",
    "Raghogarh-Vijaypur",
    "Rahatgarh",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rau",
    "Rehli",
    "Rewa",
    "Sabalgarh",
    "Sagar",
    "Sanawad",
    "Sarangpur",
    "Sarni",
    "Satna",
    "Sausar",
    "Sehore",
    "Sendhwa",
    "Seoni",
    "Seoni-Malwa",
    "Shahdol",
    "Shajapur",
    "Shamgarh",
    "Sheopur",
    "Shivpuri",
    "Shujalpur",
    "Sidhi",
    "Sihora",
    "Singrauli",
    "Sironj",
    "Sohagpur",
    "Tarana",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha",
    "Vijaypur",
    "Wara Seoni",
  ],
  maharashtra: [
    "Ahmednagar",
    "Akola",
    "Akot",
    "Amalner",
    "Ambejogai",
    "Amravati",
    "Anjangaon",
    "Arvi",
    "Aurangabad",
    "Bhiwandi",
    "Dhule",
    "Kalyan-Dombivali",
    "Ichalkaranji",
    "Kalyan-Dombivali",
    "Karjat",
    "Latur",
    "Loha",
    "Lonar",
    "Lonavla",
    "Mahad",
    "Malegaon",
    "Malkapur",
    "Mangalvedhe",
    "Mangrulpir",
    "Manjlegaon",
    "Manmad",
    "Manwath",
    "Mehkar",
    "Mhaswad",
    "Mira-Bhayandar",
    "Morshi",
    "Mukhed",
    "Mul",
    "Greater Mumbai",
    "Murtijapur",
    "Nagpur",
    "Nanded-Waghala",
    "Nandgaon",
    "Nandura",
    "Nandurbar",
    "Narkhed",
    "Nashik",
    "Navi Mumbai",
    "Nawapur",
    "Nilanga",
    "Osmanabad",
    "Ozar",
    "Pachora",
    "Paithan",
    "Palghar",
    "Pandharkaoda",
    "Pandharpur",
    "Panvel",
    "Parbhani",
    "Parli",
    "Partur",
    "Pathardi",
    "Pathri",
    "Patur",
    "Pauni",
    "Pen",
    "Phaltan",
    "Pulgaon",
    "Pune",
    "Purna",
    "Pusad",
    "Rahuri",
    "Rajura",
    "Ramtek",
    "Ratnagiri",
    "Raver",
    "Risod",
    "Sailu",
    "Sangamner",
    "Sangli",
    "Sangole",
    "Sasvad",
    "Satana",
    "Satara",
    "Savner",
    "Sawantwadi",
    "Shahade",
    "Shegaon",
    "Shendurjana",
    "Shirdi",
    "Shirpur-Warwade",
    "Shirur",
    "Shrigonda",
    "Shrirampur",
    "Sillod",
    "Sinnar",
    "Solapur",
    "Soyagaon",
    "Talegaon Dabhade",
    "Talode",
    "Tasgaon",
    "Thane",
    "Tirora",
    "Tuljapur",
    "Tumsar",
    "Uchgaon",
    "Udgir",
    "Umarga",
    "Umarkhed",
    "Umred",
    "Uran",
    "Uran Islampur",
    "Vadgaon Kasba",
    "Vaijapur",
    "Vasai-Virar",
    "Vita",
    "Wadgaon Road",
    "Wai",
    "Wani",
    "Wardha",
    "Warora",
    "Warud",
    "Washim",
    "Yavatmal",
    "Yawal",
    "Yevla",
  ],
  manipur: ["Imphal", "Lilong", "Mayang Imphal", "Thoubal"],
  meghalaya: ["Nongstoin", "Shillong", "Tura"],
  mizoram: ["Aizawl", "Lunglei", "Saiha"],
  nagaland: [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
  ],
  odisha: [
    "Balangir",
    "Baleshwar Town",
    "Barbil",
    "Bargarh",
    "Baripada Town",
    "Bhadrak",
    "Bhawanipatna",
    "Bhubaneswar",
    "Brahmapur",
    "Byasanagar",
    "Cuttack",
    "Dhenkanal",
    "Jatani",
    "Jharsuguda",
    "Kendrapara",
    "Kendujhar",
    "Malkangiri",
    "Nabarangapur",
    "Paradip",
    "Parlakhemundi",
    "Pattamundai",
    "Phulabani",
    "Puri",
    "Rairangpur",
    "Rajagangapur",
    "Raurkela",
    "Rayagada",
    "Sambalpur",
    "Soro",
    "Sunabeda",
    "Sundargarh",
    "Talcher",
    "Tarbha",
    "Titlagarh",
  ],
  puducherry: ["Karaikal", "Mahe", "Pondicherry", "Yanam"],
  punjab: [
    "Amritsar",
    "Barnala",
    "Batala",
    "Bathinda",
    "Dhuri",
    "Faridkot",
    "Fazilka",
    "Firozpur",
    "Firozpur Cantt.",
    "Gobindgarh",
    "Gurdaspur",
    "Hoshiarpur",
    "Jagraon",
    "Jalandhar Cantt.",
    "Jalandhar",
    "Kapurthala",
    "Khanna",
    "Kharar",
    "Kot Kapura",
    "Longowal",
    "Ludhiana",
    "Malerkotla",
    "Malout",
    "Mansa",
    "Moga",
    "Mohali",
    "Morinda, India",
    "Mukerian",
    "Muktsar",
    "Nabha",
    "Nakodar",
    "Nangal",
    "Nawanshahr",
    "Pathankot",
    "Patiala",
    "Pattran",
    "Patti",
    "Phagwara",
    "Phillaur",
    "Qadian",
    "Raikot",
    "Rajpura",
    "Rampura Phul",
    "Rupnagar",
    "Samana",
    "Sangrur",
    "Sirhind Fatehgarh Sahib",
    "Sujanpur",
    "Sunam",
    "Talwara",
    "Tarn Taran",
    "Urmar Tanda",
    "Zira",
    "Zirakpur",
  ],
  rajasthan: [
    {city: "Ajmer"},
    {city: "Alwar"},
    {city: "Bikaner"},
    {city: "Bharatpur"},
    {city: "Bhilwara"},
    {city: "Jaipur"},
    {city: "Jodhpur"},
    {city: "Lachhmangarh"},
    {city: "Ladnu"},
    {city: "Lakheri"},
    {city: "Lalsot"},
    {city: "Losal"},
    {city: "Makrana"},
    {city: "Malpura"},
    {city: "Mandalgarh"},
    {city: "Mandawa"},
    {city: "Mangrol"},
    {city: "Merta City"},
    {city: "Mount Abu"},
    {city: "Nadbai"},
    {city: "Nagar"},
    {city: "Nagaur"},
    {city: "Nasirabad"},
    {city: "Nathdwara"},
    {city: "Neem-Ka-Thana"},
    {city: "Nimbahera"},
    {city: "Nohar"},
    {city: "Nokha"},
    {city: "Pali"},
    {city: "Phalodi"},
    {city: "Phulera"},
    {city: "Pilani"},
    {city: "Pilibanga"},
    {city: "Pindwara"},
    {city: "Pipar City"},
    {city: "Prantij"},
    {city: "Pratapgarh"},
    {city: "Raisinghnagar"},
    {city: "Rajakhera"},
    {city: "Rajaldesar"},
    {city: "Rajgarh (Alwar)"},
    {city: "Rajgarh (Churu)"},
    {city: "Rajsamand"},
    {city: "Ramganj Mandi"},
    {city: "Ramngarh"},
    {city: "Ratangarh"},
    {city: "Rawatbhata"},
    {city: "Rawatsar"},
    {city: "Reengus"},
    {city: "Sadri"},
    {city: "Sadulshahar"},
    {city: "Sadulpur"},
    {city: "Sagwara"},
    {city: "Sambhar"},
    {city: "Sanchore"},
    {city: "Sangaria"},
    {city: "Sardarshahar"},
    {city: "Sawai Madhopur"},
    {city: "Shahpura"},
    {city: "Shahpura"},
    {city: "Sheoganj"},
    {city: "Sikar"},
    {city: "Sirohi"},
    {city: "Sojat"},
    {city: "Sri Madhopur"},
    {city: "Sujangarh"},
    {city: "Sumerpur"},
    {city: "Suratgarh"},
    {city: "Taranagar"},
    {city: "Todabhim"},
    {city: "Todaraisingh"},
    {city: "Tonk"},
    {city: "Udaipur"},
    {city: "Udaipurwati"},
    {city: "Vijainagar, Ajmer"},
  ],
  tamil_nadu: [
    "Arakkonam",
    "Aruppukkottai",
    "Chennai",
    "Coimbatore",
    "Erode",
    "Gobichettipalayam",
    "Kancheepuram",
    "Karur",
    "Lalgudi",
    "Madurai",
    "Manachanallur",
    "Nagapattinam",
    "Nagercoil",
    "Namagiripettai",
    "Namakkal",
    "Nandivaram-Guduvancheri",
    "Nanjikottai",
    "Natham",
    "Nellikuppam",
    "Neyveli (TS)",
    "O' Valley",
    "Oddanchatram",
    "P.N.Patti",
    "Pacode",
    "Padmanabhapuram",
    "Palani",
    "Palladam",
    "Pallapatti",
    "Pallikonda",
    "Panagudi",
    "Panruti",
    "Paramakudi",
    "Parangipettai",
    "Pattukkottai",
    "Perambalur",
    "Peravurani",
    "Periyakulam",
    "Periyasemur",
    "Pernampattu",
    "Pollachi",
    "Polur",
    "Ponneri",
    "Pudukkottai",
    "Pudupattinam",
    "Puliyankudi",
    "Punjaipugalur",
    "Ranipet",
    "Rajapalayam",
    "Ramanathapuram",
    "Rameshwaram",
    "Rasipuram",
    "Salem",
    "Sankarankoil",
    "Sankari",
    "Sathyamangalam",
    "Sattur",
    "Shenkottai",
    "Sholavandan",
    "Sholingur",
    "Sirkali",
    "Sivaganga",
    "Sivagiri",
    "Sivakasi",
    "Srivilliputhur",
    "Surandai",
    "Suriyampalayam",
    "Tenkasi",
    "Thammampatti",
    "Thanjavur",
    "Tharamangalam",
    "Tharangambadi",
    "Theni Allinagaram",
    "Thirumangalam",
    "Thirupuvanam",
    "Thiruthuraipoondi",
    "Thiruvallur",
    "Thiruvarur",
    "Thuraiyur",
    "Tindivanam",
    "Tiruchendur",
    "Tiruchengode",
    "Tiruchirappalli",
    "Tirukalukundram",
    "Tirukkoyilur",
    "Tirunelveli",
    "Tirupathur",
    "Tirupathur",
    "Tiruppur",
    "Tiruttani",
    "Tiruvannamalai",
    "Tiruvethipuram",
    "Tittakudi",
    "Udhagamandalam",
    "Udumalaipettai",
    "Unnamalaikadai",
    "Usilampatti",
    "Uthamapalayam",
    "Uthiramerur",
    "Vadakkuvalliyur",
    "Vadalur",
    "Vadipatti",
    "Valparai",
    "Vandavasi",
    "Vaniyambadi",
    "Vedaranyam",
    "Vellakoil",
    "Vellore",
    "Vikramasingapuram",
    "Viluppuram",
    "Virudhachalam",
    "Virudhunagar",
    "Viswanatham",
  ],
  telangana: [
    "Adilabad",
    "Bellampalle",
    "Bhadrachalam",
    "Bhainsa",
    "Bhongir",
    "Bodhan",
    "Farooqnagar",
    "Gadwal",
    "Hyderabad",
    "Jagtial",
    "Jangaon",
    "Kagaznagar",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Koratla",
    "Kothagudem",
    "Kyathampalle",
    "Mahbubnagar",
    "Mancherial",
    "Mandamarri",
    "Manuguru",
    "Medak",
    "Miryalaguda",
    "Nagarkurnool",
    "Narayanpet",
    "Nirmal",
    "Nizamabad",
    "Palwancha",
    "Ramagundam",
    "Sadasivpet",
    "Sangareddy",
    "Siddipet",
    "Sircilla",
    "Suryapet",
    "Tandur",
    "Vikarabad",
    "Wanaparthy",
    "Warangal",
    "Yellandu",
  ],
  tripura: [
    "Agartala",
    "Belonia",
    "Dharmanagar",
    "Kailasahar",
    "Khowai",
    "Pratapgarh",
    "Udaipur",
  ],
  uttar_pradesh: [
    {city: "Achhnera"},
    {city: "Agra"},
    {city: "Aligarh"},
    {city: "Allahabad"},
    {city: "Amroha"},
    {city: "Azamgarh"},
    {city: "Bahraich"},
    {city: "Chandausi"},
    {city: "Etawah"},
    {city: "Firozabad"},
    {city: "Fatehpur Sikri"},
    {city: "Hapur"},
    {city: "Hardoi "},
    {city: "Jhansi"},
    {city: "Kalpi"},
    {city: "Kanpur"},
    {city: "Khair"},
    {city: "Laharpur"},
    {city: "Lakhimpur"},
    {city: "Lal Gopalganj Nindaura"},
    {city: "Lalitpur"},
    {city: "Lalganj"},
    {city: "Lar"},
    {city: "Loni"},
    {city: "Lucknow"},
    {city: "Mathura"},
    {city: "Meerut"},
    {city: "Modinagar"},
    {city: "Moradabad"},
    {city: "Nagina"},
    {city: "Najibabad"},
    {city: "Nakur"},
    {city: "Nanpara"},
    {city: "Naraura"},
    {city: "Naugawan Sadat"},
    {city: "Nautanwa"},
    {city: "Nawabganj"},
    {city: "Nehtaur"},
    {city: "Niwai"},
    {city: "Noida"},
    {city: "Noorpur"},
    {city: "Obra"},
    {city: "Orai"},
    {city: "Padrauna"},
    {city: "Palia Kalan"},
    {city: "Parasi"},
    {city: "Phulpur"},
    {city: "Pihani"},
    {city: "Pilibhit"},
    {city: "Pilkhuwa"},
    {city: "Powayan"},
    {city: "Pukhrayan"},
    {city: "Puranpur"},
    {city: "Purquazi"},
    {city: "Purwa"},
    {city: "Rae Bareli"},
    {city: "Rampur"},
    {city: "Rampur Maniharan"},
    {city: "Rampur Maniharan"},
    {city: "Rasra"},
    {city: "Rath"},
    {city: "Renukoot"},
    {city: "Reoti"},
    {city: "Robertsganj"},
    {city: "Rudauli"},
    {city: "Rudrapur"},
    {city: "Sadabad"},
    {city: "Safipur"},
    {city: "Saharanpur"},
    {city: "Sahaspur"},
    {city: "Sahaswan"},
    {city: "Sahawar"},
    {city: "Sahjanwa"},
    {city: "Saidpur"},
    {city: "Sambhal"},
    {city: "Samdhan"},
    {city: "Samthar"},
    {city: "Sandi"},
    {city: "Sandila"},
    {city: "Sardhana"},
    {city: "Seohara"},
    {city: "Shahabad, Hardoi"},
    {city: "Shahabad, Rampur"},
    {city: "Shahganj"},
    {city: "Shahjahanpur"},
    {city: "Shamli"},
    {city: "Shamsabad, Agra"},
    {city: "Shamsabad, Farrukhabad"},
    {city: "Sherkot"},
    {city: "Shikarpur, Bulandshahr"},
    {city: "Shikohabad"},
    {city: "Shishgarh"},
    {city: "Siana"},
    {city: "Sikanderpur"},
    {city: "Sikandra Rao"},
    {city: "Sikandrabad"},
    {city: "Sirsaganj"},
    {city: "Sirsi"},
    {city: "Sitapur"},
    {city: "Soron"},
    {city: "Suar"},
    {city: "Sultanpur"},
    {city: "Sumerpur"},
    {city: "Tanda"},
    {city: "Thakurdwara"},
    {city: "Thana Bhawan"},
    {city: "Tilhar"},
    {city: "Tirwaganj"},
    {city: "Tulsipur"},
    {city: "Tundla"},
    {city: "Ujhani"},
    {city: "Unnao"},
    {city: "Utraula"},
    {city: "Varanasi"},
    {city: "Vrindavan"},
    {city: "Warhapur"},
    {city: "Zaidpur"},
    {city: "Zamania"},
  ],
  uttarakhand: [
    "Bageshwar",
    "Dehradun",
    "Haldwani-cum-Kathgodam",
    "Hardwar",
    "Kashipur",
    "Manglaur",
    "Mussoorie",
    "Nagla",
    "Nainital",
    "Pauri",
    "Pithoragarh",
    "Ramnagar",
    "Rishikesh",
    "Roorkee",
    "Rudrapur",
    "Sitarganj",
    "Srinagar",
    "Tehri",
  ],
  west_bengal: [
    "Adra",
    "Alipurduar",
    "Arambagh",
    "Asansol",
    "Baharampur",
    "Balurghat",
    "Bankura",
    "Darjiling",
    "English Bazar",
    "Gangarampur",
    "Habra",
    "Hugli-Chinsurah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kharagpur",
    "Kolkata",
    "Mainaguri",
    "Malda",
    "Mathabhanga",
    "Medinipur",
    "Memari",
    "Monoharpur",
    "Murshidabad",
    "Nabadwip",
    "Naihati",
    "Panchla",
    "Pandua",
    "Paschim Punropara",
    "Purulia",
    "Raghunathpur",
    "Raghunathganj",
    "Raiganj",
    "Rampurhat",
    "Ranaghat",
    "Sainthia",
    "Santipur",
    "Siliguri",
    "Sonamukhi",
    "Srirampore",
    "Suri",
    "Taki",
    "Tamluk",
    "Tarakeswar",
  ],
};

export const categories = [
    // {category: "Oxygen Cylinder"},
    {category: "Plasma Donor"},
    {category: "Hospital Bed"},
    {category: "Ventilator"},
    // {category: "Medicines"},
    {category: "Doctor"},
    // {category: "Necessities"},
    {category: "Ambulance"}
]
